export enum AppAction {
  SET_FIELD_RES = "SET_FIELD_RES",
  SET_IS_SHOW_FIELD = "SET_IS_SHOW_FIELD",
  SET_IS_SHOW_ISOLINES = "SET_IS_SHOW_ISOLINES",
  SET_IS_ROUNDING_FIELD = "SET_IS_ROUNDING_FIELD",
  GENERATE_NEW_FIELD = "GENERATE_NEW_FIELD"
}
